# PyTorch & Tensorflow

## Pytorch 

오픈소스 머신러닝 플랫폼

부가 질문 : 도식화 한 후 코딩하나요? 
- 파이토치는 도식화가 안되도 진행 가능, 텐서플로우는 불가능 
  - tensor board : 과정 보는 프로그램
  

Tensorflow - google개발

Pytorch - facebook개발
(구현속도 더 빠름)

## Tensor and Types
Tensor(자료형)


소수점 32 : torch.float32, torch.float

소수점 64 : torch.float64, torch.double

소수점 16 : torch.float16, torch.half

8-bit integer(unsigned) : torch.uint8

8-bit integer(signed) : torch.int8

16-bit integer(signed) : torch.int16, torch.short

32-bit integer(signed) : torch.int32, torch.int

64-bit integer(signed) : torch.int64, torch.long

In [4]:
t = [[1,2,3], [4,5,6], [7,8,9]]
print(t)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


## Pytorch Basic

In [3]:
import torch
# 0에서 1사이의 랜덤한 숫자 
x = torch.rand(2,3) 
print(x) 
 
# 정규분포에서 샘플링한 값 
x = torch.randn(2,3) 
print(x) 

# 시작과 끝 사이의 랜덤한 자연수 
x = torch.randint(2,5,size = (2,3))
print(x)

tensor([[0.6128, 0.9268, 0.1238],
        [0.5221, 0.9639, 0.6112]])
tensor([[-0.0194,  0.7699,  0.1883],
        [ 0.5799, -1.0038, -1.7866]])
tensor([[3, 2, 3],
        [4, 3, 2]])


In [7]:
# 0으로 채워진 텐서 
x = torch.zeros(2,3)
print(x) 

# 인자로 들어오는 텐서와 형태가 같은 0로 채워진 텐서 
ref = torch.rand(4,5) 
x = torch.zeros_like(ref)
print(x) 

# 1로 채워진 텐서 
x = torch.ones(2,3) 
print(x) 

# 인자로 들어오는 텐서와 형태가 같은 1로 채워진 텐서 
ref = torch.rand(4,5)
x = torch.ones_like(ref)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


## Perceptron with pytorch 

In [16]:
import torch 
import torch.nn as nn # feedforaward를 하기 위한 대부분의 함수를 가지고 있음 
import numpy as np 

x_data = torch.FloatTensor([1.0,2.0])
print(x_data)

linear = nn.Linear(2,1) # 입력으로 들어오는 퍼셉트론 수, 출력으로 나가는 퍼셉트론 수 
print(linear(x_data)) # w1,w2,bias 다 계산한 값, 새롭게 계산할 때 마다 값이 바뀜

sigmoid = nn.Sigmoid() # sigmoid function 계산해 주는 함수

z = sigmoid(linear(x_data)) 
print(z)

## relu 써서 풀어보기 숙제 
# relu = nn.ReLU() 
# nn.LeakyReLu()  # 좀 더 계산이 정확하게 나오는 함수
# z = relu(linear(x_data))

tensor([1., 2.])
tensor([1.5358], grad_fn=<AddBackward0>)
tensor([0.8229], grad_fn=<SigmoidBackward>)


In [19]:
linear.weight # weight값 나옴

Parameter containing:
tensor([[0.6418, 0.5571]], requires_grad=True)

In [18]:
linear.bias # 가중치의 값이 나옴 

Parameter containing:
tensor([-0.2202], requires_grad=True)

In [22]:
# 실제로 확인해보면 두 개의 값이 같음 
print(1 * 0.6418 + 2 * 0.5571 - 0.2202)
print(linear(x_data))

1.5358000000000003
tensor([1.5358], grad_fn=<AddBackward0>)
